neutron/ide/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.conf import settings
from django.views.generic.simple import redirect_to

urlpatterns = patterns('ide.views',
  url('^filetree/$', 'filetree', name='ide-filetree'),
  url('^dirchooser/$', 'dirchooser', name='ide-dirchooser'),
  url('^fileget/$', 'fileget', name='ide-fileget'),
  url('^filesave/$', 'filesave', name='ide-filesave'),
  url('^compile/$', 'compile', name='ide-compile'),
  url('^run/$', 'run', name='ide-compile'),
  url('^accounts/login/$', 'login', name='ide-login'),
  url('^favicon.ico$', redirect_to, {'url': settings.STATIC_URL + 'ide/img/favicon.ico'}, name='ide-favicon.ico'),
  url('^new/$', 'new', name='ide-new'),
  url('^delete/$', 'remove', name='ide-delete'),
  url('^rename/$', 'rename', name='ide-rename'),
  url('^temp_file/$', 'temp_file', name='ide-temp-file'),
  url('^view_file(?P<fp>.+)$', 'view_file', name='ide-view-file'),
  url('^external_open(?P<fp>.+)$', 'external_open', name='ide-ext-open'),
  url('^save_image(?P<fp>.+)$', 'save_image', name='ide-save-image'),
  url('^external_request/(?P<key>.+)/fp(?P<fp>.+)$', 'external_request', name='ide-ext-req'),
  url('^save_session/$', 'save_session', name='ide-save-session'),
  
  url('^editor_pref/$', 'editor_pref', name='ide-editor-pref'),
  url('^term_pref/$', 'term_pref', name='ide-terminal-pref'),
  
  url('^dir_search/$', 'submit_search', name='ide-dir-search'),
  url('^check_search/$', 'check_search', name='ide-check-search'),
  
  url('^dir_replace/$', 'submit_replace', name='ide-dir-replace'),
  url('^check_replace/$', 'check_replace', name='ide-check-replace'),
  url('^cancel_job/$', 'cancel_job', name='ide-cancel-job'),
  
  url('^terminal/$', 'terminal', name='ide-terminal'),
  
  url('^$', 'home', name='ide-home'),
)

neutron/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin
from django.conf import settings

admin.autodiscover()

urlpatterns = patterns('',
  url(r'^admin/', include(admin.site.urls)),
  url(r'', include('neutron.ide.urls')),
)

if settings.DJANGO_SERVE_STATIC_MEDIA:
  urlpatterns += patterns('',
    url(r'^%s(?P<path>.*)$' % settings.STATIC_URL[1:-1], 'django.views.static.serve',  {'document_root': settings.STATIC_ROOT, 'show_indexes': True}),
  )
  
if settings.DJANGO_SERVE_STATIC_MEDIA or settings.DEBUG:
  urlpatterns += patterns('',
    url(r'^%s(?P<path>.*)$' % settings.MEDIA_URL[1:-1], 'django.views.static.serve',  {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
  )
  

neutron/ide/models.py
import os
import re
import time
import glob
import cPickle as pickle

from django.db import models
from django.contrib.auth.models import User
import django.utils.simplejson as json

from ide.grep import Grep
from ide.templatetags.ntags import hashstr

THEMES = (
  ('textmate', 'TextMate'),
  ('eclipse', 'Eclipse'),
  ('dawn', 'Dawn'),
  ('idle_fingers', 'idleFingers'),
  ('pastel_on_dark', 'Pastel on dark'),
  ('twilight', 'Twilight'),
  ('clouds', 'Clouds'),
  ('clouds_midnight', 'Clouds Midnight'),
  ('crimson_editor', 'Crimson'),
  ('kr_theme', 'krTheme'),
  ('mono_industrial', 'Mono Industrial'),
  ('monokai', 'Monokai'),
  ('merbivore', 'Merbivore'),
  ('merbivore_soft', 'Merbivore Soft'),
  ('vibrant_ink', 'Vibrant Ink'),
  ('solarized_dark', 'Solarized Dark'),
  ('solarized_light', 'Solarized Light'),
)

UI_THEMES = (
  ('default', 'Default'),
  ('black', 'Black'),
  ('blueopal', 'Blue Opal'),
  #('hakama', 'Hakama'),
  ('metro', 'Metro'),
  ('silver', 'Silver')
)

SIZES = (
  ('6px', '6px'),
  ('7px', '7px'),
  ('8px', '8px'),
  ('9px', '9px'),
  ('10px', '10px'),
  ('11px', '11px'),
  ('12px', '12px'),
  ('13px', '13px'),
  ('14px', '14px'),
  ('15px', '15px'),
  ('16px', '16px'),
  ('17px', '17px'),
  ('18px', '18px'),
  ('19px', '19px'),
  ('20px', '20px'),
  ('21px', '21px'),
  ('22px', '22px'),
  ('23px', '23px'),
  ('24px', '24px'),
)

KBINDS = (
  ('ace', 'Ace'),
  ('vim', 'Vim'),
  ('emacs', 'Emacs')
)

WRAPS = (
  ('off', 'Off'),
  ('40', '40 Chars'),
  ('80', '80 Chars'),
  ('free', 'Free')
)

class TempFile (models.Model):
  user = models.ForeignKey(User)
  file = models.FileField(upload_to='tmp')
  
class ExtFileRequest (models.Model):
  secret = models.CharField(max_length=255)
  path = models.TextField(max_length=255)
  created = models.DateTimeField(auto_now_add=True)
  
class Preferences (models.Model):
  user = models.OneToOneField(User)

  basedir = models.CharField('Base Directory', max_length=255)
  
  uitheme = models.CharField('UI Theme', choices=UI_THEMES, max_length=25, default='default')
  
  theme = models.CharField('Editor Theme', choices=THEMES, max_length=25, default='textmate')
  fontsize = models.CharField('Font Size', choices=SIZES, max_length=10, default='12px')
  keybind = models.CharField('Key Bindings', choices=KBINDS, max_length=10, default='ace')
  swrap = models.CharField('Soft Wrap', choices=WRAPS, max_length=10, default='off')
  
  tabsize = models.IntegerField('Tab Size', default=4)
  
  hactive = models.BooleanField('Highlight Active Line', default=True)
  hword = models.BooleanField('Highlight Selected Word', default=True)
  invisibles = models.BooleanField('Show Invisibles', default=False)
  gutter = models.BooleanField('Show Gutter', default=True)
  pmargin = models.BooleanField('Show Print Margin', default=True)
  softab = models.BooleanField('Use Soft Tab', default=True)
  behave = models.BooleanField('Enable Behaviors', default=True)
  splitterm = models.BooleanField('Use Split Terminal/IDE', default=True)
  
  save_session = models.BooleanField('Save Session', default=True)
  session = models.TextField(blank=True, null=True)

  guide_tour = models.BooleanField('Guide Tour', default=True)
  
  bg = models.ImageField('Terminal Background Image', blank=True, null=True, upload_to='bg')
  font = models.CharField('Terminal Font', max_length=255, default='"Courier New", Courier, "Lucida Sans Typewriter", "Lucida Typewriter", monospace')
  tfontsize = models.CharField('Terminal Font Size', max_length=25, default='13px')
  
  def last_session (self):
    if self.session:
      return json.dumps(self.session.split("\n"))
      
    return '[]';
    
  def valid_path (self, path):
    path = os.path.normpath(path)
    if path.startswith(self.basedir):
      return True
      
    return False
    
class DirSearch (models.Model):
  user = models.ForeignKey(User)
  opts = models.TextField()
  
  state = models.CharField(max_length=25, default='created')
  replace_state = models.CharField(max_length=25, blank=True, null=True)
  
  results = models.TextField(blank=True, null=True)
  replace_results = models.TextField(blank=True, null=True)
  
  created = models.DateTimeField(auto_now_add=True)
  updated = models.DateTimeField(auto_now=True)
  
  killed = models.BooleanField(default=False)
  
  class Meta:
    verbose_name = 'Directory Search Job'
    
  def make_needle (self):
    needle = ''
    opts = self.get_opts()
    
    regex = False
    flags = re.I
    
    if opts['caseSensitive'] == 'true':
      flags = 0
      
    if opts['regExp'] == 'true':
      regex = True
      
    if regex:
      if opts['wholeWord'] == 'true':
        needle = re.compile(r"\b" + opts['needle'] + r"\b", flags=flags)
        
      else:
        needle = re.compile(opts['needle'], flags=flags)
        
    else:
      if opts['wholeWord'] == 'true':
        needle = re.compile(r"\b" + re.escape(opts['needle'] + r"\b"), flags=flags)
        
      else:
        needle = re.compile(re.escape(opts['needle']), flags=flags)
        
    return needle
    
  def do_search (self):
    self.state = 'running'
    self.save()
    opts = self.get_opts()
    needle = self.make_needle()
    results = []
    
    for root, dirs, files in os.walk(opts['dir']):
      if opts['glob']:
        files = glob.glob(root + '/' + opts['glob'])
        
      if files:
        for file in files:
          if JobKill.objects.filter(ds=self).count() > 0:
            self.killed = True
            self.save()
            print 'Job Killed'
            return
            
          fp = os.path.join(root, file)
          uid = hashstr(fp)
          
          if opts['needle']:
            grep = Grep(fp, needle)
            grep_results = grep.results()
            if grep_results:
              results.append((fp, uid, grep_results))
              
          else:
            results.append((fp, uid, []))
            
        self.set_results(results)
        
    self.state = 'complete'
    self.save()
    
  def do_replace (self):
    self.replace_state = 'running'
    self.save()
    
    for r in self.get_results():
      if JobKill.objects.filter(ds=self).count() > 0:
        self.killed = True
        self.save()
        print 'Job Killed'
        return
        
      needle = self.make_needle()
      opts = self.get_opts()
      rlines = [x[0] for x in r[2]]
      
      grep = Grep(r[0], needle)
      grep.replace(opts['replace'], rlines)
      if self.replace_results:
        self.replace_results += '\n' + r[0]
        
      else:
        self.replace_results = r[0]
        
      self.save()
      
    self.replace_state = 'complete'
    self.save()
    
  def get_opts (self):
    return pickle.loads(str(self.opts))
    
  def get_results (self):
    return pickle.loads(str(self.results))
    
  def set_results (self, results):
    self.results = pickle.dumps(results)
    self.save()
    
class JobKill (models.Model):
  ds = models.ForeignKey(DirSearch)
  created = models.DateTimeField(auto_now_add=True)
  

neutron/ide/forms.py
from django import forms

import ide.models

class EditorPref (forms.ModelForm):
  class Meta:
    model = ide.models.Preferences
    exclude = ('user', 'basedir', 'session', 'bg', 'font', 'tfontsize')
    
class TermPref (forms.ModelForm):
  class Meta:
    model = ide.models.Preferences
    exclude = ('user', 'basedir', 'session', 'uitheme', 'theme', 'fontsize', \
               'keybind', 'swrap', 'tabsize', 'hactive', 'hword', 'invisibles', \
               'gutter', 'pmargin', 'softab', 'behave', 'save_session', 'splitterm')
               
    

neutron/ide/templates/ide/close.html
<!DOCTYPE html>
<html> 
  <head>
    <meta charset="utf-8"/> 
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <title>So Long And Thanks For All The Fish</title>
  </head>
  <body>
    <h1>So Long And Thanks For All The Fish</h1>
    <script type="text/javascript">
      window.close();
    </script>
  </body>
</html>

neutron/ide/templates/ide/editor_pref.html
{% extends "ide/master_iframe.html" %}
{% block content %}
<form action="" method="post" class="pref_form">
  {% csrf_token %}
  <table>
    <tr>
      <td>
        {% if form.errors.uitheme %}{{ form.errors.uitheme }}{% endif %}
        UI Theme: {{ form.uitheme }}
      </td>
      <td>
        {% if form.errors.theme %}{{ form.errors.theme }}{% endif %}
        Editor Theme: {{ form.theme }}
      </td>
    </tr>
    <tr>
      <td>
        {% if form.errors.keybind %}{{ form.errors.keybind }}{% endif %}
        Key Bindings: {{ form.keybind }}
      </td>
      <td>
        {% if form.errors.swrap %}{{ form.errors.swrap }}{% endif %}
        Soft Wrap: {{ form.swrap }}
      </td>
    </tr>
    <tr>
      <td>
        {% if form.errors.fontsize %}{{ form.errors.fontsize }}{% endif %}
        Font Size: {{ form.fontsize }}
      </td>
      <td>
        {% if form.errors.tabsize %}{{ form.errors.tabsize }}{% endif %}
        Tab Size: {{ form.tabsize }}
      </td>
    </tr>
    <tr>
      <td colspan="2">
        <table>
          <tr>
            <td>
              {{ form.hactive }} <label for="id_hactive">Highlight Active Line</label>
            </td>
            <td>
              {{ form.hword }} <label for="id_hword">Highlight Selected Word</label>
            </td>
          </tr>
          <tr>
            <td>
              {{ form.invisibles }} <label for="id_invisibles">Show Invisibles</label>
            </td>
            <td>
              {{ form.gutter }} <label for="id_gutter">Show Gutter</label>
            </td>
          </tr>
          <tr>
            <td>
              {{ form.pmargin }} <label for="id_pmargin">Show Print Margin</label>
            </td>
            <td>
              {{ form.softab }} <label for="id_softab">Use Soft Tab</label>
            </td>
          </tr>
          <tr>
            <td>
              {{ form.behave }} <label for="id_behave">Enable Behaviors</label>
            </td>
            <td>{{ form.save_session }} <label for="id_save_session">Save Session</label></td>
          </tr>
          <tr>
            <td>
              {{ form.splitterm }} <label for="id_splitterm">Use Split Terminal/IDE</label>
            </td>
            <td>{{ form.guide_tour }} <label for="id_guide_tour">Show Guide Tour</label></td>
          </tr>
        </table>
      </td>
    </tr>
    <tr>
      <td colspan="2">
        <input type="submit" name="task" value="Save"/>
      </td>
    </tr>
  </table>
</form>
{% endblock %}

neutron/ide/templates/ide/editor_pref_success.html
{% extends "ide/master_iframe.html" %}
{% block content %}
<h1 class="message">So Long And Thanks<br/>For All The Fish!</h1>
{% endblock %}
{% block footer %}
<script type="text/javascript">
  parent.update_prefs({{ new_prefs|safe }});
</script>
{% endblock %}

neutron/ide/templates/ide/home.html
{% extends "ide/master.html" %}{% load ntags %}
{% block head %}
{% with pref=request.user.preferences %}
<script type="text/javascript">
  var pref = {
    uitheme: '{{ pref.uitheme }}',
    
    theme: '{{ pref.theme }}',
    fontsize: '{{ pref.fontsize }}',
    keybind: '{{ pref.keybind }}',
    swrap: '{{ pref.swrap }}',
    tabsize: {{ pref.tabsize }},
    
    hactive: {{ pref.hactive|js_bool }},
    hword: {{ pref.hword|js_bool }},
    invisibles: {{ pref.invisibles|js_bool }},
    gutter: {{ pref.gutter|js_bool }},
    pmargin: {{ pref.pmargin|js_bool }},
    softab: {{ pref.softab|js_bool }},
    behave: {{ pref.behave|js_bool }},
    
    save_session: {{ pref.save_session|js_bool }},
  };
  
  var init_session = {{ pref.last_session|safe }};
  var skip_session = true;
  var basedir = "{{ pref.basedir }}";
  var loaded_themes = ['{{ pref.theme }}'];
  var static_url = '{{ STATIC_URL }}';
  var track_ajax = {% if request.track %}true{% else %}false{% endif %};
  
  {% if pref.splitterm and TERMINAL_ON %}
  var splitterm = true;
  {% else %}
  var splitterm = false;
  {% endif %}
</script>
<style type="text/css">
  .ace_editor { font-size: {{ pref.fontsize }}; }
</style>
{% endwith %}
{% endblock %}
{% block content %}
<div id="neutron_ui">
  <div id="neutron_menubar">
    <span id="logo" class="logo">Neutron IDE v12.06</span>
    <button class="k-button" onclick="SaveCurrentTab()">Save</button>
    <button class="k-button" onclick="SaveAll()">Save All</button>
    <button class="k-button" onclick="CloseAll()">Close All</button>
    <button id="menu_button" class="k-button" onclick="return show_menu()"><img src="{{ STATIC_URL }}ide/img/menu.png" alt="Menu" title="Menu"/></button>
    <div style="display: inline-block"><input type="text" id="quick_search"/></div>
    <div id="current_edit">Welcome to Neutron IDE</div>
    <div id="status"></div>
  </div>
  <div id="neutron_body">
    <div id="splitter">
      <div id="splitter_left">
        <div id="tooltabs">
          <ul>
            <li id="fbtab">Files</li>
            <li id="searchtab">Search</li>
          </ul>
          <div>
            <div id="file_browser">
              <a href="javascript: void(0)">File Browser</a>
              <div class="inner"></div>
            </div>
          </div>
          <div>
            {% include "ide/search_tab.html" %}
          </div>
        </div>
      </div>
      <div id="splitter_right" style="height: 100%;">
        {% if request.user.preferences.splitterm and TERMINAL_ON %}
        <div id="ide_top">
          <div id="tabs">
            <div id="tabsinner">
              <ul></ul>
            </div>
          </div>
          <div id="editor_global"></div>
        </div>
        <div id="ide_bottom">
          <!--<iframe width="100%" height="300" frameBorder="0" scrolling="auto" src="/terminal/"></iframe>-->
        </div>
        {% else %}
        <div id="tabs">
          <div id="tabsinner">
            <ul></ul>
          </div>
        </div>
        <div id="editor_global"></div>
        {% endif %}
      </div>
    </div>
  </div>
</div>
{% include "ide/right_menu_dir.html" %}
{% endblock %}
{% block footer %}
<div id="main_menu">
  <ul>
    <li><a href="javascript: void(0)" onclick="show_pref()" class="pref">Editor Preferences</a></li>
    <li class="btop">
      <span class="submenu">
        <span class="arrow">&raquo;</span>Editor Mode
        <ul class="emodes">
          {% for mode in MODES %}<li><a href="javascript: void(0)" onclick="set_editor_mode('{{ mode.0 }}')">{{ mode.1 }}</a></li>
          {% endfor %}
        </ul>
        <div class="clear"></div>
      </span>
    </li>
    <li class="btop">
      <span class="submenu">
        <span class="arrow">&raquo;</span>Help! 
        <ul>
          <li><a href="https://github.com/pizzapanther/Neutron-IDE/wiki/Default-Key-Bindings" target="_blank" class="link">Key Bindings</a></li>
          <li><a href="https://github.com/pizzapanther/Neutron-IDE/wiki/Emacs-Key-Bindings" target="_blank" class="link">EMacs Key Bindings</a></li>
          <li><a href="https://github.com/pizzapanther/Neutron-IDE/wiki/Vim-Key-Bindings" target="_blank" class="link">Vim Key Bindings</a></li>
          <li><a href="http://neutronide.com/" target="_blank" class="link">NeutronIDE.com</a></li>
        </ul>
      </span>
    </li>
    {% if TERMINAL_ON %}
    <li><a href="{% url ide-terminal %}" target="_blank" class="term">Terminal</a></li>
    <li><a href="javascript: void(0)" onclick="window.open('{% url ide-terminal %}', '_blank', 'height=400,width=650,location=no,menubar=no,status=no,titlebar=no,toolbar=no,top=0,left=0')" class="term">Terminal (Pop Up)</a></li>
    {% endif %}
    <li><a href="javascript: void(0)" onclick="about()" class="about">About</a></li>
  </ul>
</div>
{% endblock %}

neutron/ide/templates/ide/master.html
<!DOCTYPE html>
<html> 
  <head>
	{% block mainhead %}
    <meta charset="utf-8"/> 
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <title>{% block title %}Neutron IDE &sdot; {{ request.get_host }}{% endblock %}</title>
    <link rel="shortcut icon" href="{{ STATIC_URL }}ide/img/favicon.ico" />
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,400,700' rel='stylesheet' type='text/css'/>
    <link href='https://fonts.googleapis.com/css?family=Droid+Sans+Mono' rel='stylesheet' type='text/css'/>
    <link href='https://fonts.googleapis.com/css?family=VT323&v1' rel='stylesheet' type='text/css'>
    
    <link href='{{ STATIC_URL }}ide/js/jqueryFileTree/jqueryFileTree.css' rel='stylesheet' type='text/css'>
    <link href='{{ STATIC_URL }}ide/css/kendo_styles/kendo.common.min.css' rel='stylesheet' type='text/css'/>
    <link href='{{ STATIC_URL }}ide/css/default.css' rel='stylesheet' type='text/css'/>
    <link href='{{ STATIC_URL }}ide/css/kendo_styles/kendo.{{ request.user.preferences.uitheme }}.min.css' id="kendoStyle" rel='stylesheet' type='text/css'/>
    
    <script type="text/javascript" src='{{ STATIC_URL }}ide/js/jquery.js'></script>
    <script type="text/javascript" src='{{ STATIC_URL }}ide/js/jqueryFileTree/jqueryFileTree.js'></script>
    <script type="text/javascript" src='{{ STATIC_URL }}ide/js/jquery-ui/js/jquery-ui-1.8.13.custom.min.js'></script>
    <script type="text/javascript" src='{{ STATIC_URL }}ide/js/kendo.all.min.js'></script>
    <script type="text/javascript" src='{{ STATIC_URL }}ide/js/ace/build/src/ace.js'></script>
    {% for mode in MODES %}{% if mode.0 != 'text' %}<script src="{{ STATIC_URL }}ide/js/ace/build/src/mode-{{ mode.0 }}.js" type="text/javascript"></script>
    {% endif %}{% endfor %}
    {% for theme in THEMES %}{% if theme == request.user.preferences.theme %}<script src="{{ STATIC_URL }}ide/js/ace/build/src/theme-{{ theme }}.js" type="text/javascript"></script>{% endif %}{% endfor %}
    <script type="text/javascript" src='{{ STATIC_URL }}ide/js/ace/build/src/keybinding-emacs.js'></script>
    <script type="text/javascript" src='{{ STATIC_URL }}ide/js/ace/build/src/keybinding-vim.js'></script>
    <script type="text/javascript" src='{{ STATIC_URL }}ide/js/common.js'></script>
    <script type="text/javascript" src='{{ STATIC_URL }}ide/js/default.js'></script>
    <script type="text/javascript" src='{{ STATIC_URL }}ide/js/menu.js'></script>
    <script type="text/javascript" src='{{ STATIC_URL }}ide/js/modals.js'></script>
    <script type="text/javascript" src='{{ STATIC_URL }}ide/js/search.js'></script>
    {% endblock %}
    {% block head %}{% endblock %}
    {% if request.track %}{{ request.track_code|safe }}{% endif %}
  </head>
  <body>
    {% block content %}{% endblock %}
    {% block footer %}{% endblock %}
    <div style="display: none;">
      {% include "ide/modals.html" %}
    </div>
  </body>
</html>

neutron/ide/templates/ide/master_iframe.html
<!DOCTYPE html>
<html>
  <head>
    {% block mainhead %}
    <meta charset="utf-8"/> 
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <title>{% block title %}Neutron IDE &sdot; {{ request.get_host }}{% endblock %}</title>
    <link rel="shortcut icon" href="{{ STATIC_URL }}ide/img/favicon.ico" />
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,400,700' rel='stylesheet' type='text/css'/>
    <link href='https://fonts.googleapis.com/css?family=Droid+Sans+Mono&v1' rel='stylesheet' type='text/css'/>
    <link href='https://fonts.googleapis.com/css?family=VT323&v1' rel='stylesheet' type='text/css'>
    
    <link href='{{ STATIC_URL }}ide/css/iframe.css' rel='stylesheet' type='text/css'>
    <link href='{{ STATIC_URL }}ide/css/kendo_styles/kendo.{{ request.user.preferences.uitheme }}.min.css' rel='stylesheet' type='text/css'/>
	
    
    <script type="text/javascript" src='{{ STATIC_URL }}ide/js/jquery.js'></script>
    <script type="text/javascript" src='{{ STATIC_URL }}ide/js/iframe.js'></script>
    
    {% endblock %}
    {% block head %}{% endblock %}
  </head>
  <body class="k-content">
    {% block content %}{% endblock %}
    {% block footer %}{% endblock %}
  </body>
</html>

neutron/ide/templates/ide/message.html
{% extends "ide/master.html" %}
{% block mainhead %}{% endblock %}
{% block content %}
<h1>{{ message }}</h1>
{% endblock %}
{% block footer %}{% endblock %}

neutron/ide/templates/ide/right_menu_dir.html
<script type="text/javascript">
  $("#{{ did }}_right").remove();
  $('body').append(
  '<div id="{{ did }}_right" class="right_menu">\
  <ul>\
    <li class="fd">{{ d }}</li>\
    <li class="btop"><a href="javascript: void(0)" onclick="new_stuff(\'{{ d }}\', \'{{ dir|escapejs }}\', \'{{ did }}\')" class="new">New File/Dir</a></li>\
    <li><a href="javascript: void(0)" onclick="refresh_dir(\'{{ did }}\')" class="refresh">Refresh</a></li>\
    {% if did != 'file_browser' %}<li><a href="javascript: rename(\'{{ dir }}\', \'{{ did }}\')" class="rename">Rename</a></li>{% endif %}\
    {% if did != 'file_browser' %}<li><a href="javascript: delete_me(\'{{ dir }}\', \'{{ did }}\')" class="delete">Delete</a></li>{% endif %}\
  </ul>\
</div>' 
  );
  $("#{{ did }} > a").bind('contextmenu rightclick',  function(e) {
    $(".right_menu").css("display", 'none');
    
    var did = "{{ did }}";
    
    $("#{{ did }}_right").css("display", 'block');
    
    var t = e.pageY - 20;
    var h = $("#{{ did }}_right").height();
    var bottom = t + h;
    var doch = $(window).height();
    if (bottom > doch) {
      t = doch - h;
    }
    
    $("#{{ did }}_right").css("top", t + 'px');
    
    var ol = e.pageX - 20;
    $("#{{ did }}_right").css("left", ol + 'px');
    e.preventDefault();
    return false;
  });
</script>

neutron/ide/templates/ide/term_pref.html
{% extends "ide/master_iframe.html" %}
{% block head %}
<base target="_blank">
<style type="text/css">
  input[type="text"] {
    width: 400px;
  }
  
  input#id_tfontsize {
    width: 40px;
  }
</style>
{% endblock %}
{% block content %}
<form action="{% url ide-terminal-pref %}" method="post" class="pref_form" enctype="multipart/form-data" target="_self">
  {% csrf_token %}
  <table>
    <tr>
      <td>
        {% if form.errors.bg %}{{ form.errors.bg }}{% endif %}
        <strong>Background Image</strong>:<br>{{ form.bg }}
      </td>
    </tr>
    <tr>
      <td>
        {% if form.errors.tfontsize %}{{ form.errors.tfontsize }}{% endif %}
        <strong>Font Size</strong>:<br>{{ form.tfontsize }}
      </td>
    </tr>
    <tr>
      <td>
        {% if form.errors.font %}{{ form.errors.font }}{% endif %}
        <strong>Font</strong>:<br>{{ form.font }}
      </td>
    </tr>
    <tr>
      <td colspan="2">
        <input type="submit" name="task" value="Save"/>
      </td>
    </tr>
  </table>
</form>
{% endblock %}

neutron/ide/templates/ide/term_pref_success.html
{% extends "ide/master_iframe.html" %}
{% block content %}
<h1 class="message">Hold On To Your Butts!</h1>
{% endblock %}
{% block footer %}
<script type="text/javascript">
  parent.update_prefs_term({{ new_prefs|safe }});
</script>
{% endblock %}